---
resources:
- name: 2m
  type: time
  source: {interval: 2m}

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: 2m
    trigger: true
  - task: hello-world
    params:
      REDIS_HOST: ((redis-host))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: joshuamckenty/scimmia}
      run:
        path: /home/scimmia/test.sh
        args: []


# Maybe use https://github.com/concourse/concourse-pipeline-resource
# to unpause the test scripts once the upgrade starts?